# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

driver = webdriver.Chrome()
vars = {}


driver.get("http://127.0.0.1:5500/login.html")
driver.set_window_size(1301, 720)
driver.find_element(By.ID, "username").click()
driver.find_element(By.ID, "username").send_keys("Tanay")
driver.find_element(By.ID, "password").send_keys("12345")
driver.find_element(By.CSS_SELECTOR, "button").click()
driver.find_element(By.CSS_SELECTOR, ".settings_account-inner:nth-child(4) > .settings__left--account-content").click()
driver.find_element(By.CSS_SELECTOR, ".button:nth-child(1)").click()
driver.find_element(By.CSS_SELECTOR, ".button:nth-child(2)").click()
driver.find_element(By.CSS_SELECTOR, ".toDeliver button").click()
driver.find_element(By.CSS_SELECTOR, ".settings_account-inner:nth-child(5)").click()
driver.find_element(By.CSS_SELECTOR, "button").click()
driver.find_element(By.CSS_SELECTOR, ".settings_account-inner:nth-child(6) .settings__left--account-name").click()
driver.find_element(By.ID, "currentPassword").click()
driver.find_element(By.ID, "currentPassword").send_keys("1234")
driver.find_element(By.ID, "newPassword").send_keys("123456")
driver.find_element(By.ID, "confirmPassword").send_keys("123456")
driver.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()
driver.find_element(By.LINK_TEXT, "Back to Main Menu").click()
driver.find_element(By.CSS_SELECTOR, ".LogOutBtn").click()

driver.quit()
